// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getrefreshtoken.sql

package database

import (
	"context"
)

const lookupRefreshToken = `-- name: LookupRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at 
FROM refreshtokens
WHERE token = $1
`

func (q *Queries) LookupRefreshToken(ctx context.Context, token string) (Refreshtoken, error) {
	row := q.db.QueryRowContext(ctx, lookupRefreshToken, token)
	var i Refreshtoken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
